### ISSUE TITLE
! LaTeX Error: \usepackage before \documentclass.

### ISSUE THREAD

**Issue by chaosmail** [woife/discrete_mathematics_lecture_notes#1]
Hi guys,

Thanks for the great work! I have an error when generating the pdf file. The old version from bitbucket compiles like charm, whereas this throws the following error:

```
pdflatex main.tex
This is pdfTeX, Version 3.14159265-2.6-1.40.15 (TeX Live 2015/dev/Debian) (preloaded format=pdflatex)
 restricted \write18 enabled.
entering extended mode
(./main.tex
LaTeX2e <2014/05/01>
Babel <3.9l> and hyphenation patterns for 4 languages loaded.
\@input{preamble.aux}
(./preamble.tex

! LaTeX Error: \usepackage before \documentclass.

See the LaTeX manual or LaTeX Companion for explanation.
Type  H <return>  for immediate help.
 ...                                              

Best,
Christoph

**Comment by sanssecours** [comment]
Hi Christoph,

it looks like you translated the “wrong” file. Most probably you want to compile [lecture_notes_A4.tex](https://github.com/woife/discrete_mathematics_lecture_notes/blob/master/lecture_notes_A4.tex). To fix this problem you can edit line 6 of `Makefile`:

```make
MAIN_TEX = lecture_notes_A4
```
and compile the document via `make`. An other option is to translate the file directly via something like `pdflatex lecture_notes_A4` or even better `latexmk -pdf lecture_notes_A4`.

Kind regards,
  René

**Comment by chaosmail** [comment]
Great thanks!
